# Sets up the following variables
#	OSG_GEO_OSG_LIBRARY
#	OSG_GEO_OSG_LIBRARY
#	OSG_GEO_OSGGA_LIBRARY
#	OSG_GEO_OSGUTIL_LIBRARY
#	OSG_GEO_OSGDB_LIBRARY
#	OSG_GEO_OSGTEXT_LIBRARY
#	OSG_GEO_OSGWIDGET_LIBRARY
#	OSG_GEO_OSGTERRAIN_LIBRARY
#	OSG_GEO_OSGFX_LIBRARY
#	OSG_GEO_OSGVIEWER_LIBRARY
#	OSG_GEO_OSGVOLUME_LIBRARY
#	OSG_GEO_OPENTHREADS_LIBRARY
#
# Written by: Kristofer Tingdahl

SET (CMAKE_DEBUG_POSTFIX d)
LIST(APPEND CMAKE_MODULE_PATH ${osgGeo_SOURCE_DIR}/CMakeModules)
FIND_PACKAGE(OSG)

IF ( ${CMAKE_BUILD_TYPE} MATCHES "Debug" )
    SET(OSG_GEO_OSG_LIBRARY_POSTIFIX "_DEBUG" )
ENDIF()

SET ( OSG_GEO_OSG_MODULES
	OSG
	OSGGA
	OSGUTIL
	OSGDB
	OSGTEXT
	OSGWIDGET
	OSGTERRAIN
	OSGFX
	OSGVIEWER
	OSGVOLUME
	OPENTHREADS )

FOREACH( MODULE ${OSG_GEO_OSG_MODULES} )
    SET( OSG_GEO_${MODULE}_LIBRARY ${${MODULE}_LIBRARY${OSG_GEO_OSG_LIBRARY_POSTIFIX}} )
ENDFOREACH()
