# Sets up the following variables
#	OSGGEO_OSG_LIBRARY
#	OSGGEO_OSG_LIBRARY
#	OSGGEO_OSGGA_LIBRARY
#	OSGGEO_OSGUTIL_LIBRARY
#	OSGGEO_OSGDB_LIBRARY
#	OSGGEO_OSGTEXT_LIBRARY
#	OSGGEO_OSGWIDGET_LIBRARY
#	OSGGEO_OSGTERRAIN_LIBRARY
#	OSGGEO_OSGFX_LIBRARY
#	OSGGEO_OSGVIEWER_LIBRARY
#	OSGGEO_OSGVOLUME_LIBRARY
#	OSGGEO_OPENTHREADS_LIBRARY
#
#	OSGGEO_OSG_LIBRARY_PATH
#
# Written by: Kristofer Tingdahl

set(OSG_DIR "" CACHE PATH REQUIRED)
set(OSGGEO_USE_DEBUG_OSG "" CACHE BOOL REQUIRED)

set (CMAKE_DEBUG_POSTFIX d)
list(APPEND CMAKE_MODULE_PATH ${osgGeo_SOURCE_DIR}/CMakeModules)
find_package(OSG)

if ( OSGGEO_USE_DEBUG_OSG )
    set(OSGGEO_OSG_LIBRARY_POSTIFIX "_DEBUG" )
else()
    set(OSGGEO_OSG_LIBRARY_POSTIFIX )
endif()

set ( OSGGEO_OSG_MODULES
	OSG
	OSGGA
	OSGUTIL
	OSGMANIPULATOR
	OSGQT
	OSGDB
	OSGTEXT
	OSGWIDGET
	OSGTERRAIN
	OSGFX
	OSGVIEWER
	OSGVOLUME
	OPENTHREADS )

foreach( OSGMODULE ${OSGGEO_OSG_MODULES} )
    if( ${OSGMODULE}_LIBRARY_DEBUG AND
	NOT (${${OSGMODULE}_LIBRARY_DEBUG} STREQUAL ${${OSGMODULE}_LIBRARY} ) )

	set ( CUROSGLIB optimized ${${OSGMODULE}_LIBRARY}
			debug ${${OSGMODULE}_LIBRARY_DEBUG} )
    else()
	if( ${OSGMODULE}_LIBRARY_DEBUG )
	    set ( CUROSGLIB ${${OSGMODULE}_LIBRARY_DEBUG} )
	else()
	    set ( CUROSGLIB ${${OSGMODULE}_LIBRARY} )
	endif()
    endif()

    if( CUROSGLIB )
	set( OSGGEO_${OSGMODULE}_LIBRARY ${CUROSGLIB} )
    endif()
endforeach()

get_filename_component( OSGGEO_OSG_LIBRARY_PATH ${OSG_LIBRARY} PATH )
