# Sets up common variables
#	OSGGEO_LIB_POSTFIX
#	OSGGEO_MAKE_LAUNCHERS
#
# Written by: Kristofer Tingdahl


IF(UNIX AND NOT WIN32 AND NOT APPLE)
  IF(CMAKE_SIZEOF_VOID_P MATCHES "8")
      SET(LIB_POSTFIX "64" CACHE STRING "suffix for 32/64 dir placement")
      MARK_AS_ADVANCED(LIB_POSTFIX)
  ENDIF()
ELSE()
  SET(OSGGEO_MAKE_LAUNCHERS 1)
ENDIF()

IF(NOT DEFINED OSGGEO_LIB_POSTFIX)
    SET(OSGGEO_LIB_POSTFIX "")
ENDIF()
