# Sets up the following variables
#	OSGGEO_OSG_LIBRARY
#	OSGGEO_OSG_LIBRARY
#	OSGGEO_OSGGA_LIBRARY
#	OSGGEO_OSGUTIL_LIBRARY
#	OSGGEO_OSGDB_LIBRARY
#	OSGGEO_OSGTEXT_LIBRARY
#	OSGGEO_OSGWIDGET_LIBRARY
#	OSGGEO_OSGTERRAIN_LIBRARY
#	OSGGEO_OSGFX_LIBRARY
#	OSGGEO_OSGVIEWER_LIBRARY
#	OSGGEO_OSGVOLUME_LIBRARY
#	OSGGEO_OPENTHREADS_LIBRARY
#
#	OSGGEO_OSG_LIBRARY_PATH
#
# Written by: Kristofer Tingdahl

SET(OSG_DIR "" CACHE PATH REQUIRED)
SET(OSGGEO_USE_DEBUG_OSG "" CACHE BOOL REQUIRED)

SET (CMAKE_DEBUG_POSTFIX d)
LIST(APPEND CMAKE_MODULE_PATH ${osgGeo_SOURCE_DIR}/CMakeModules)
FIND_PACKAGE(OSG)

IF ( OSGGEO_USE_DEBUG_OSG )
    SET(OSGGEO_OSG_LIBRARY_POSTIFIX "_DEBUG" )
ELSE()
    SET(OSGGEO_OSG_LIBRARY_POSTIFIX )
ENDIF()

SET ( OSGGEO_OSG_MODULES
	OSG
	OSGGA
	OSGUTIL
	OSGDB
	OSGTEXT
	OSGWIDGET
	OSGTERRAIN
	OSGFX
	OSGVIEWER
	OSGVOLUME
	OPENTHREADS )

FOREACH( OSGMODULE ${OSGGEO_OSG_MODULES} )
    IF ( ${CMAKE_BUILD_TYPE} MATCHES "Debug" )
	IF ( ${OSGMODULE}_LIBRARY_DEBUG )
	    SET( CUROSGLIB ${${OSGMODULE}_LIBRARY_DEBUG} )
	ELSE()
	    IF ( NOT ${OSGMODULE}_LIBRARY )
		MESSAGE(FATAL_ERROR "${OSGMODULE}_LIBRARY is missing")
	    ELSE()
		SET( CUROSGLIB ${${OSGMODULE}_LIBRARY} )
	    ENDIF()
	ENDIF()
    ELSE()
	IF ( ${OSGMODULE}_LIBRARY )
	    SET( CUROSGLIB ${${OSGMODULE}_LIBRARY} )
	ELSE()
	    IF ( NOT ${OSGMODULE}_LIBRARY_DEBUG )
		MESSAGE(FATAL_ERROR "${OSGMODULE}_LIBRARY is missing")
	    ELSE()
		SET( CUROSGLIB ${${OSGMODULE}_LIBRARY_DEBUG} )
	    ENDIF()
	ENDIF()

    ENDIF()

    IF( CUROSGLIB )
	SET( OSGGEO_${OSGMODULE}_LIBRARY ${CUROSGLIB} )
    ENDIF()
ENDFOREACH()

GET_FILENAME_COMPONENT(OSGGEO_OSG_LIBRARY_PATH ${OSGGEO_OSG_LIBRARY} PATH )
